name: duck-sync
on:
  schedule:
    - cron: '14 8-23/7 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-duck-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync duck-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/okyyds/duck.git"
          source_branch: "master"
          destination_branch: "duck"
          github_token: ${{ secrets.PAT }}
